// src/app/routes/add/add.component.ts
import { Component, ChangeDetectionStrategy } from "@angular/core";
import { UntypedFormBuilder, Validators } from "@angular/forms";
import { Router } from "@angular/router";
import { VerifyStates, VerifyState } from "src/app/interfaces/item";

@Component({
    selector: 'add',
    templateUrl: './add.component.html',
    styleUrls: ['./add.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AddComponent {
    form = this.fb.group({
        title: ['', Validators.compose([Validators.required, Validators.maxLength(40)])],
        password: ['', Validators.compose([Validators.minLength(4), Validators.maxLength(100)])],
        icon: [''],
    })
    hide = true;
    constructor(private fb: UntypedFormBuilder, private router: Router) {}

    add() {
        if(!this.form.valid){
            return
        }
        this.router.navigateByUrl("/verify", {
            state: {
                forEncrypt: [
                    {
                        title: this.form.get('title')?.value as string,
                        password: this.form.get('password')?.value as string,
                    }
                ],
                state: VerifyStates.Encrypt,
            } as VerifyState
        })
    }

    goHome() {
        this.router.navigateByUrl("/")
    }
}
<div class="verify-form" [formGroup]="form">
    <mat-form-field appearance="fill">
        <mat-label>{{ 'ENTER_TITLE'| translate }}</mat-label>
        <input matInput formControlName="title" autocomplete="off">
        <mat-error *ngIf="form.get('title')!.invalid">{{ 'TITLE_VALIDATION'| translate }}</mat-error>
    </mat-form-field>
    <mat-form-field appearance="fill">
        <mat-label>{{ 'ENTER_PASSWORD'| translate }}</mat-label>
        <input matInput formControlName="password" [type]="hide ? 'password' : 'text'">
        <button mat-icon-button matSuffix (click)="hide = !hide" [attr.aria-label]="'Hide password'"
            [attr.aria-pressed]="hide">
            <mat-icon>{{hide ? 'visibility_off' : 'visibility'}}</mat-icon>
        </button>
        <mat-error *ngIf="form.get('password')!.invalid">{{ 'PASSWORD_VALIDATION'| translate }}</mat-error>
    </mat-form-field>
    <section>
        <button mat-flat-button color="primary" (click)="add()">{{ 'ADD'| translate }}</button>
        <button mat-stroked-button (click)="goHome()">{{ 'BACK'| translate }}</button>
    </section>
</div>

// src/screens/Add.svelte
<script lang="ts">
  import { t } from '../lib/i18n';
  import { go, goHome } from '../lib/nav.svelte';
  import PasswordField from '../components/PasswordField.svelte';

  let title = $state('');
  let password = $state('');
  let touched = $state(false);

  const titleInvalid = $derived(title.trim().length === 0 || title.length > 40);
  const passwordInvalid = $derived(password.length < 4 || password.length > 100);

  function submit(event: SubmitEvent) {
    event.preventDefault();
    touched = true;
    if (titleInvalid || passwordInvalid) {
      return;
    }
    go({
      name: 'verify',
      mode: 'encrypt',
      forEncrypt: [{ title: title.trim(), password }],
    });
  }
</script>

<form class="panel" onsubmit={submit}>
  <div class="field-wrap">
    <span class="field-label">{t('ENTER_TITLE')}</span>
    <input class="field" bind:value={title} maxlength="40" autocomplete="off" />
    <span class="field-error">{touched && titleInvalid ? t('TITLE_VALIDATION') : ''}</span>
  </div>

  <PasswordField bind:value={password} label={t('ENTER_PASSWORD')}
    error={touched && passwordInvalid ? t('PASSWORD_VALIDATION') : ''} />

  <section class="actions">
    <button type="submit" class="btn">{t('ADD')}</button>
    <button type="button" class="btn btn-stroked" onclick={goHome}>{t('BACK')}</button>
  </section>
</form>
